# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/reserva.ui'
#
# Created: Thu Apr 15 16:37:41 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_reservaDialog(object):
    def setupUi(self, reservaDialog):
        reservaDialog.setObjectName("reservaDialog")
        reservaDialog.resize(400, 375)
        self.gridLayout = QtGui.QGridLayout(reservaDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtGui.QDialogButtonBox(reservaDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(reservaDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.unidadCombo = QtGui.QComboBox(reservaDialog)
        self.unidadCombo.setObjectName("unidadCombo")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.unidadCombo)
        self.label_2 = QtGui.QLabel(reservaDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.huespedLine = QtGui.QLineEdit(reservaDialog)
        self.huespedLine.setObjectName("huespedLine")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.huespedLine)
        self.label_3 = QtGui.QLabel(reservaDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_3)
        self.inicioPreDate = QtGui.QDateEdit(reservaDialog)
        self.inicioPreDate.setCalendarPopup(True)
        self.inicioPreDate.setObjectName("inicioPreDate")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.inicioPreDate)
        self.label_4 = QtGui.QLabel(reservaDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_4)
        self.finPreDate = QtGui.QDateEdit(reservaDialog)
        self.finPreDate.setCalendarPopup(True)
        self.finPreDate.setObjectName("finPreDate")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.finPreDate)
        self.label_5 = QtGui.QLabel(reservaDialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_5)
        self.inicioDate = QtGui.QDateEdit(reservaDialog)
        self.inicioDate.setCalendarPopup(True)
        self.inicioDate.setObjectName("inicioDate")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.inicioDate)
        self.label_6 = QtGui.QLabel(reservaDialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_6)
        self.finDate = QtGui.QDateEdit(reservaDialog)
        self.finDate.setCalendarPopup(True)
        self.finDate.setObjectName("finDate")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.finDate)
        self.label_7 = QtGui.QLabel(reservaDialog)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_7)
        self.inTime = QtGui.QTimeEdit(reservaDialog)
        self.inTime.setObjectName("inTime")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.inTime)
        self.label_8 = QtGui.QLabel(reservaDialog)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_8)
        self.outTime = QtGui.QTimeEdit(reservaDialog)
        self.outTime.setObjectName("outTime")
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.outTime)
        self.label_9 = QtGui.QLabel(reservaDialog)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_9)
        self.estadoCombo = QtGui.QComboBox(reservaDialog)
        self.estadoCombo.setObjectName("estadoCombo")
        self.estadoCombo.addItem("")
        self.estadoCombo.addItem("")
        self.estadoCombo.addItem("")
        self.estadoCombo.addItem("")
        self.estadoCombo.addItem("")
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.estadoCombo)
        self.huespedView = QtGui.QTableView(reservaDialog)
        self.huespedView.setObjectName("huespedView")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.huespedView)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)

        self.retranslateUi(reservaDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), reservaDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), reservaDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(reservaDialog)
        reservaDialog.setTabOrder(self.huespedLine, self.buttonBox)

    def retranslateUi(self, reservaDialog):
        reservaDialog.setWindowTitle(QtGui.QApplication.translate("reservaDialog", "Nueva unidad", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("reservaDialog", "Unidad:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("reservaDialog", "Huesped:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("reservaDialog", "Inicio Prereserva:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("reservaDialog", "Fin Prereserva:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("reservaDialog", "Inicio Reserva:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("reservaDialog", "Fin Reserva:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("reservaDialog", "Hora CheckIn:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("reservaDialog", "Hora CheckOut:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("reservaDialog", "Estado:", None, QtGui.QApplication.UnicodeUTF8))
        self.estadoCombo.setItemText(0, QtGui.QApplication.translate("reservaDialog", "Pre Reservado", None, QtGui.QApplication.UnicodeUTF8))
        self.estadoCombo.setItemText(1, QtGui.QApplication.translate("reservaDialog", "Reservado", None, QtGui.QApplication.UnicodeUTF8))
        self.estadoCombo.setItemText(2, QtGui.QApplication.translate("reservaDialog", "Reserva en curso", None, QtGui.QApplication.UnicodeUTF8))
        self.estadoCombo.setItemText(3, QtGui.QApplication.translate("reservaDialog", "Reserva terminada", None, QtGui.QApplication.UnicodeUTF8))
        self.estadoCombo.setItemText(4, QtGui.QApplication.translate("reservaDialog", "Reserva cancelada", None, QtGui.QApplication.UnicodeUTF8))

