# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grilla.ui'
#
# Created: Fri Jun 25 16:42:56 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Grilla(object):
    def setupUi(self, Grilla):
        Grilla.setObjectName("Grilla")
        Grilla.resize(621, 509)
        self.gridLayout_2 = QtGui.QGridLayout(Grilla)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.mesCombo = QtGui.QComboBox(Grilla)
        self.mesCombo.setObjectName("mesCombo")
        self.mesCombo.addItem("")
        self.mesCombo.addItem("")
        self.mesCombo.addItem("")
        self.mesCombo.addItem("")
        self.mesCombo.addItem("")
        self.mesCombo.addItem("")
        self.mesCombo.addItem("")
        self.mesCombo.addItem("")
        self.mesCombo.addItem("")
        self.mesCombo.addItem("")
        self.mesCombo.addItem("")
        self.mesCombo.addItem("")
        self.gridLayout.addWidget(self.mesCombo, 0, 2, 1, 1)
        self.anioSpin = QtGui.QSpinBox(Grilla)
        self.anioSpin.setMinimum(2000)
        self.anioSpin.setMaximum(3000)
        self.anioSpin.setObjectName("anioSpin")
        self.gridLayout.addWidget(self.anioSpin, 0, 4, 1, 1)
        self.label = QtGui.QLabel(Grilla)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(Grilla)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 5, 1, 1)
        self.tableWidget = QtGui.QTableWidget(Grilla)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 6)
        self.frame = QtGui.QFrame(Grilla)
        self.frame.setMinimumSize(QtCore.QSize(0, 30))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label_5 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(15, 15))
        self.label_5.setMaximumSize(QtCore.QSize(15, 15))
        self.label_5.setStyleSheet("background-color: rgb(111, 183, 231);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.label_10 = QtGui.QLabel(self.frame)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.label_4 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(15, 15))
        self.label_4.setMaximumSize(QtCore.QSize(15, 15))
        self.label_4.setStyleSheet("background-color: rgb(255, 207, 14);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.label_8 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(15, 15))
        self.label_8.setMaximumSize(QtCore.QSize(15, 15))
        self.label_8.setStyleSheet("background-color: rgb(34, 227, 99);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.label_3 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(15, 15))
        self.label_3.setMaximumSize(QtCore.QSize(15, 15))
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.gridLayout.addWidget(self.frame, 4, 0, 1, 6)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Grilla)
        QtCore.QMetaObject.connectSlotsByName(Grilla)

    def retranslateUi(self, Grilla):
        Grilla.setWindowTitle(QtGui.QApplication.translate("Grilla", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.mesCombo.setItemText(0, QtGui.QApplication.translate("Grilla", "Enero", None, QtGui.QApplication.UnicodeUTF8))
        self.mesCombo.setItemText(1, QtGui.QApplication.translate("Grilla", "Febrero", None, QtGui.QApplication.UnicodeUTF8))
        self.mesCombo.setItemText(2, QtGui.QApplication.translate("Grilla", "Marzo", None, QtGui.QApplication.UnicodeUTF8))
        self.mesCombo.setItemText(3, QtGui.QApplication.translate("Grilla", "Abril", None, QtGui.QApplication.UnicodeUTF8))
        self.mesCombo.setItemText(4, QtGui.QApplication.translate("Grilla", "Mayo", None, QtGui.QApplication.UnicodeUTF8))
        self.mesCombo.setItemText(5, QtGui.QApplication.translate("Grilla", "Junio", None, QtGui.QApplication.UnicodeUTF8))
        self.mesCombo.setItemText(6, QtGui.QApplication.translate("Grilla", "Julio", None, QtGui.QApplication.UnicodeUTF8))
        self.mesCombo.setItemText(7, QtGui.QApplication.translate("Grilla", "Agosto", None, QtGui.QApplication.UnicodeUTF8))
        self.mesCombo.setItemText(8, QtGui.QApplication.translate("Grilla", "Septiembre", None, QtGui.QApplication.UnicodeUTF8))
        self.mesCombo.setItemText(9, QtGui.QApplication.translate("Grilla", "Octubre", None, QtGui.QApplication.UnicodeUTF8))
        self.mesCombo.setItemText(10, QtGui.QApplication.translate("Grilla", "Noviembre", None, QtGui.QApplication.UnicodeUTF8))
        self.mesCombo.setItemText(11, QtGui.QApplication.translate("Grilla", "Diciembre", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Grilla", "Mes:", None, QtGui.QApplication.UnicodeUTF8))
