# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'huesped.ui'
#
# Created: Fri Jul 16 19:41:46 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_huespedDialog(object):
    def setupUi(self, huespedDialog):
        huespedDialog.setObjectName("huespedDialog")
        huespedDialog.resize(400, 388)
        huespedDialog.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Spain))
        self.gridLayout = QtGui.QGridLayout(huespedDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtGui.QDialogButtonBox(huespedDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(huespedDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.dniLine = QtGui.QLineEdit(huespedDialog)
        self.dniLine.setObjectName("dniLine")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.dniLine)
        self.label_2 = QtGui.QLabel(huespedDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.apellidoLine = QtGui.QLineEdit(huespedDialog)
        self.apellidoLine.setObjectName("apellidoLine")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.apellidoLine)
        self.label_3 = QtGui.QLabel(huespedDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.nombreLine = QtGui.QLineEdit(huespedDialog)
        self.nombreLine.setObjectName("nombreLine")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.nombreLine)
        self.label_4 = QtGui.QLabel(huespedDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.telLine = QtGui.QLineEdit(huespedDialog)
        self.telLine.setObjectName("telLine")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.telLine)
        self.label_5 = QtGui.QLabel(huespedDialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.celLine = QtGui.QLineEdit(huespedDialog)
        self.celLine.setObjectName("celLine")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.celLine)
        self.label_6 = QtGui.QLabel(huespedDialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtGui.QLabel(huespedDialog)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_7)
        self.direccionLine = QtGui.QLineEdit(huespedDialog)
        self.direccionLine.setObjectName("direccionLine")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.direccionLine)
        self.localidadLine = QtGui.QLineEdit(huespedDialog)
        self.localidadLine.setObjectName("localidadLine")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.localidadLine)
        self.label_8 = QtGui.QLabel(huespedDialog)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtGui.QLabel(huespedDialog)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtGui.QLabel(huespedDialog)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtGui.QLabel(huespedDialog)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_11)
        self.emailLine = QtGui.QLineEdit(huespedDialog)
        self.emailLine.setObjectName("emailLine")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.emailLine)
        self.patenteLine = QtGui.QLineEdit(huespedDialog)
        self.patenteLine.setObjectName("patenteLine")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.patenteLine)
        self.modeloLine = QtGui.QLineEdit(huespedDialog)
        self.modeloLine.setObjectName("modeloLine")
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.modeloLine)
        self.colorLine = QtGui.QLineEdit(huespedDialog)
        self.colorLine.setObjectName("colorLine")
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.colorLine)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)

        self.retranslateUi(huespedDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), huespedDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), huespedDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(huespedDialog)
        huespedDialog.setTabOrder(self.dniLine, self.apellidoLine)
        huespedDialog.setTabOrder(self.apellidoLine, self.nombreLine)
        huespedDialog.setTabOrder(self.nombreLine, self.telLine)
        huespedDialog.setTabOrder(self.telLine, self.buttonBox)

    def retranslateUi(self, huespedDialog):
        huespedDialog.setWindowTitle(QtGui.QApplication.translate("huespedDialog", "Nuevo Huésped", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("huespedDialog", "* DNI:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("huespedDialog", "* Apellido:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("huespedDialog", "* Nombre:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("huespedDialog", "Teléfono fijo:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("huespedDialog", "Celular:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("huespedDialog", "Dirección:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("huespedDialog", "Localidad:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("huespedDialog", "e-mail:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("huespedDialog", "Patente del Auto:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("huespedDialog", "Modelo del Auto:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("huespedDialog", "Color del Auto:", None, QtGui.QApplication.UnicodeUTF8))

