# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwin.ui'
#
# Created: Thu Apr 15 16:11:38 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(583, 562)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.options = QtGui.QListWidget(self.centralwidget)
        self.options.setMaximumSize(QtCore.QSize(155, 16777215))
        self.options.setIconSize(QtCore.QSize(150, 84))
        self.options.setGridSize(QtCore.QSize(150, 80))
        self.options.setObjectName("options")
        self.gridLayout.addWidget(self.options, 0, 0, 1, 1)
        self.title = QtGui.QGroupBox(self.centralwidget)
        self.title.setObjectName("title")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.title)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widgets = QtGui.QStackedWidget(self.title)
        self.widgets.setObjectName("widgets")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.page)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.widgets.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.widgets.addWidget(self.page_2)
        self.verticalLayout_4.addWidget(self.widgets)
        self.gridLayout.addWidget(self.title, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 583, 20))
        self.menubar.setObjectName("menubar")
        self.menuAdministracion = QtGui.QMenu(self.menubar)
        self.menuAdministracion.setObjectName("menuAdministracion")
        self.menuAcerca_de = QtGui.QMenu(self.menubar)
        self.menuAcerca_de.setObjectName("menuAcerca_de")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNueva_unidad = QtGui.QAction(MainWindow)
        self.actionNueva_unidad.setObjectName("actionNueva_unidad")
        self.actionNuevo_Tipo = QtGui.QAction(MainWindow)
        self.actionNuevo_Tipo.setObjectName("actionNuevo_Tipo")
        self.actionSalir = QtGui.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionAcerca_de = QtGui.QAction(MainWindow)
        self.actionAcerca_de.setObjectName("actionAcerca_de")
        self.actionAyuda = QtGui.QAction(MainWindow)
        self.actionAyuda.setObjectName("actionAyuda")
        self.menuAdministracion.addAction(self.actionNueva_unidad)
        self.menuAdministracion.addAction(self.actionNuevo_Tipo)
        self.menuAdministracion.addSeparator()
        self.menuAdministracion.addAction(self.actionSalir)
        self.menuAcerca_de.addAction(self.actionAcerca_de)
        self.menuAcerca_de.addAction(self.actionAyuda)
        self.menubar.addAction(self.menuAdministracion.menuAction())
        self.menubar.addAction(self.menuAcerca_de.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.title.setTitle(QtGui.QApplication.translate("MainWindow", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", " Bienvenido!", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAdministracion.setTitle(QtGui.QApplication.translate("MainWindow", "Administracion", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAcerca_de.setTitle(QtGui.QApplication.translate("MainWindow", "Ayuda", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNueva_unidad.setText(QtGui.QApplication.translate("MainWindow", "Nueva unidad", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNuevo_Tipo.setText(QtGui.QApplication.translate("MainWindow", "Nuevo Tipo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSalir.setText(QtGui.QApplication.translate("MainWindow", "Salir", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAcerca_de.setText(QtGui.QApplication.translate("MainWindow", "Acerca de...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAyuda.setText(QtGui.QApplication.translate("MainWindow", "Ayuda", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
